component_depth: 1

exclude:
  - /telegram.sh
  - /data/src/main/java/io/forus/me/android/data/entity/validators/.*
  - /presentation/src/main/java/io/forus/me/android/presentation/view/screens/.*
  - /data/src/main/java/io/forus/me/android/data/entity/vouchers/response/.*
  - /data/src/main/java/io/forus/me/android/data/entity/records/response/.*
