component_depth: 1

exclude:
  - /data/src/main/java/io/forus/me/android/data/entity/validators/.*
  - /presentation/src/main/java/io/forus/me/android/presentation/view/screens/vouchers/list/VouchersPresenter.kt
  - /presentation/src/main/java/io/forus/me/android/presentation/view/screens/account/assigndelegates/email/RestoreByEmailFragment.kt
