image: javiersantos/android-ci:28.0.3

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - build

#build:
#  stage: build
#  script:
#    - cd presentation
#    - ../gradlew assembleDebug
##  artifacts:
##    paths:
##      - app/build/outputs/apk/

build:
  stage: build
  only:
  - development
  script:
  - cd presentation
  - ../gradlew assembleDebug
