image: jangrewe/gitlab-ci-android

stages:
- telegram

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/


telegram:
  stage: telegram
  only:
  - development
  script:
  - cd presentation
  - ../gradlew  assembleDebug
